# Generated by Django 3.1.5 on 2021-01-31 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210131_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksofusers',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
